complete javascript-loops
K-Karneboge/rc0822-code-solutions pull request #30
Opened 2022-09-01 22:36 UTC by K-Karneboge

![image](https://user-images.githubusercontent.com/20393497/188024368-cfd128b6-eda5-4856-b27a-0424523768cc.png)

2022-09-01 23:01 UTC, Zhiwutian requested changes
Looking good! A couple small updates. Make sure to reach out if you have questions!

2022-09-01 23:01 UTC, Zhiwutian commented on javascript-loops/main.js
> +  for (var i = 0; i < object.length; i++) {
you want to make sure to use a `for in` loop here. Objects do not have a length property.

2022-09-01 23:01 UTC, BrettAlbright commented on javascript-loops/main.js
> +  for (object.keys in object) {
here you want to define a variable for the for in loop

for (var property in object)

then you have access to the individual keys.

2022-09-02 06:49 UTC, K-Karneboge commented
![image](https://user-images.githubusercontent.com/20393497/188076012-c4ceec13-bb6c-4e9f-8bf3-f6ac3d8fc758.png)

2022-09-02 15:28 UTC, Zhiwutian approved these changes
👍🏼

2022-09-06 13:46 UTC, merged